import { parseAbi } from "viem";

export const GATEWAY_ABI = parseAbi([
  "function createInvoice(bytes32 merchantInvoiceId, address payIn, uint256 amountOut, uint64 expiresAt) external returns (bytes32 globalId)",
  "function createInvoiceFor(address merchant, bytes32 merchantInvoiceId, address payIn, uint256 amountOut, uint64 expiresAt) external returns (bytes32 globalId)",
  "function authorizeDelegate(address delegate, uint64 expiresAt) external",
  "function revokeDelegate(address delegate) external",
  "function registerMerchant(address payoutAddress, address payoutToken) external",
  "function updatePayoutAddress(address newPayoutAddress) external",
  "function updatePayoutToken(address newPayoutToken) external",
  "function deactivateMerchant() external",
  "function pay(bytes32 globalId, uint256 maxAmountIn) external",
  "function refundInvoice(bytes32 globalId) external",
  "function withdrawFees(address token, address to) external",
  "function merchants(address) view returns (address payoutAddress, address payoutToken, bool active)",
  "function invoices(bytes32) view returns (address merchant, address payIn, address payoutToken, uint256 amountOut, uint64 expiresAt, uint8 status, address paidBy)",
  "function payments(bytes32) view returns (uint256 merchantPayout, uint256 fee)",
  "function delegateAuthorizations(address merchant, address delegate) view returns (uint64)",
  "event MerchantRegistered(address indexed merchant, address payoutAddress, address payoutToken)",
  "event MerchantPayoutAddressUpdated(address indexed merchant, address oldAddress, address newAddress)",
  "event MerchantPayoutTokenUpdated(address indexed merchant, address oldToken, address newToken)",
  "event MerchantDeactivated(address indexed merchant)",
  "event InvoiceCreated(bytes32 indexed globalId, address indexed merchant, bytes32 indexed merchantInvoiceId, address payIn, address payoutToken, uint256 amountOut, uint64 expiresAt)",
  "event InvoicePaid(bytes32 indexed globalId, address indexed payer, uint256 amountIn, uint256 grossReceived, uint256 merchantPayout, uint256 fee)",
  "event InvoiceRefunded(bytes32 indexed globalId, address indexed refundedTo, address indexed payoutToken, uint256 merchantPayout, uint256 protocolFeeReturned)",
  "event DelegateAuthorized(address indexed merchant, address indexed delegate, uint64 expiresAt)",
  "event DelegateRevoked(address indexed merchant, address indexed delegate)",
]);
